### ISSUE TITLE
diff problems with filenames with spaces in archives

### ISSUE THREAD

**Issue by ghost** [openSUSE/build-compare#23] opened 2018-05-10 17:26 UTC
pkg-diff.sh seems to have problems with filenames with spaces in archives.

Test project: https://build.opensuse.org/package/show/home:munix9:test/cannoli

Contains a TGZ archive with files that contain spaces in the filename
(archive is build on-the-fly in '%install'):

```
# l -R /data3/tmp/build-root/openSUSE_Leap_42.3-x86_64/home/abuild/rpmbuild/BUILD/
/data3/tmp/build-root/openSUSE_Leap_42.3-x86_64/home/abuild/rpmbuild/BUILD/:
total 12
drwxr-xr-x 3 399 399 4096 May 10 18:39 ./
drwxr-xr-x 9 399 399 4096 May 10 18:39 ../
drwxr-xr-x 3 399 399 4096 May 10 18:39 cannoli-0.1/

/data3/tmp/build-root/openSUSE_Leap_42.3-x86_64/home/abuild/rpmbuild/BUILD/cannoli-0.1:
total 16
drwxr-xr-x 3 399 399 4096 May 10 18:39 ./
drwxr-xr-x 3 399 399 4096 May 10 18:39 ../
drwxr-xr-x 3 399 399 4096 May 10 18:39 data/
-rw-r--r-- 1 399 399  649 May 10 18:39 data.tgz

/data3/tmp/build-root/openSUSE_Leap_42.3-x86_64/home/abuild/rpmbuild/BUILD/cannoli-0.1/data:
total 12
drwxr-xr-x 3 399 399 4096 May 10 18:39 ./
drwxr-xr-x 3 399 399 4096 May 10 18:39 ../
drwxr-xr-x 2 399 399 4096 May 10 18:39 dir/

/data3/tmp/build-root/openSUSE_Leap_42.3-x86_64/home/abuild/rpmbuild/BUILD/cannoli-0.1/data/dir:
total 32
drwxr-xr-x 2 399 399 4096 May 10 18:39 ./
drwxr-xr-x 3 399 399 4096 May 10 18:39 ../
-rw-r--r-- 1 399 399    1 May 10 18:39 A quick movement of the enemy will jeopardize six gunboats.txt
-rw-r--r-- 1 399 399    1 May 10 18:39 Five quacking Zephyrs jolt my wax bed.txt
-rw-r--r-- 1 399 399    1 May 10 18:39 Heavy boxes perform waltzes and jigs.txt
-rw-r--r-- 1 399 399    1 May 10 18:39 Sphinx of black quartz judge my vow.txt
-rw-r--r-- 1 399 399    1 May 10 18:39 The five boxing wizards jump quickly.txt
-rw-r--r-- 1 399 399    1 May 10 18:39 The quick brown fox jumps over the lazy dog.txt
```
After triggering new builds without any package change,
/usr/lib/build/pkg-diff.sh says something like
```
[   26s] compare /.build.oldpackages/cannoli-0.1-1.1.noarch.rpm /home/abuild/rpmbuild/RPMS/noarch/cannoli-0.1-1.2.noarch.rpm
[   26s] Comparing cannoli-0.1-1.1.noarch.rpm to cannoli-0.1-1.2.noarch.rpm
[   26s] comparing rpmtags
[   26s] comparing RELEASE
[   26s] comparing PROVIDES
[   26s] comparing scripts
[   26s] comparing filelist
[   26s] comparing file checksum
[   26s] creating rename script
[   26s] RPM file checksum differs.
[   26s] Extracting packages
[   26s] Missing in old package: /usr/share/cannoli/data/dir/Sphinx
[   26s] comparing /.build.oldpackages/rpmlint.log and /home/abuild/rpmbuild/OTHER/rpmlint.log
```
The filename is truncated at the space character, the package is wrongly marked as changed and the revision is increased.

**Comment by olafhering** [comment] 2018-05-24 10:15
That is caused by the way how the list of files is constructed:
````
files=`diff -U0 $file1 $file2 | fgrep -v +++ | grep ^+ | cut -b2- | awk '{print $1}'`
````
Perhaps `files` should be an array.

**Comment by bmwiedemann** [comment] 2019-04-11 08:39
Can you retry now that PR #30 is merged?

**Comment by bmwiedemann** [comment] 2024-11-06 15:07
This is probably fixed since a while.

**Closed by bmwiedemann** 2024-11-06 15:07 UTC
